import { Language } from '../types';

type TranslationKey = 
  | 'app_title' | 'app_subtitle' | 'client_secure' | 'docs'
  | 'tool_compress' | 'tool_compress_desc'
  | 'tool_convert' | 'tool_convert_desc'
  | 'tool_avif' | 'tool_avif_desc'
  | 'tool_base64' | 'tool_base64_desc'
  | 'tool_anim' | 'tool_anim_desc'
  | 'tool_decode' | 'tool_decode_desc'
  | 'upload_title_drag' | 'upload_title_click' | 'upload_support'
  | 'processing' | 'results_empty_title' | 'results_empty_desc'
  | 'did_you_know_title' | 'did_you_know_desc'
  | 'res_visual' | 'res_embed' | 'res_seo' | 'res_before' | 'res_after'
  | 'res_download' | 'res_suggested_alt' | 'res_caption' | 'res_analyzing' | 'res_waiting' | 'res_generated_by'
  | 'anim_title' | 'anim_desc' | 'anim_clear' | 'anim_speed' | 'anim_preview' | 'anim_add'
  | 'dec_title' | 'dec_paste' | 'dec_preview' | 'dec_invalid' | 'dec_placeholder'
  | 'set_title' | 'set_theme' | 'set_lang' | 'set_api' | 'set_api_desc' | 'set_api_placeholder' | 'set_api_help' | 'set_close'
  | 'set_color' | 'set_save';

const translations: Record<Language, Record<TranslationKey, string>> = {
  en: {
    app_title: 'ImageLite',
    app_subtitle: 'Studio',
    client_secure: 'Client-side Secure Processing',
    docs: 'Docs',
    tool_compress: 'Compress',
    tool_compress_desc: 'Lossless reduction',
    tool_convert: 'Convert WebP',
    tool_convert_desc: 'SEO Optimization',
    tool_avif: 'Convert AVIF',
    tool_avif_desc: 'Next-Gen Format',
    tool_base64: 'Base64',
    tool_base64_desc: 'Embed codes',
    tool_anim: 'Animation',
    tool_anim_desc: 'Create GIF loop',
    tool_decode: 'Decode',
    tool_decode_desc: 'Base64 to Image',
    upload_title_drag: 'Drop images now',
    upload_title_click: 'Click or drag images here',
    upload_support: 'Supports JPG, PNG, WebP, AVIF up to 50MB',
    processing: 'Processing your images...',
    results_empty_title: 'Results will appear here',
    results_empty_desc: 'Processed files and animations show up here.',
    did_you_know_title: 'Did you know?',
    did_you_know_desc: 'AVIF offers superior compression efficiency compared to WebP and JPEG. It provides high quality at smaller file sizes.',
    res_visual: 'Visual Compare',
    res_embed: 'Embed Code',
    res_seo: 'AI Analysis',
    res_before: 'Before',
    res_after: 'After',
    res_download: 'Download',
    res_suggested_alt: 'Suggested Alt Text',
    res_caption: 'Caption / Description',
    res_analyzing: 'Analyzing...',
    res_waiting: 'Waiting for AI...',
    res_generated_by: 'Generated by Gemini 2.5 Flash',
    anim_title: 'Animation Mode',
    anim_desc: 'Stitch multiple images into a sequence.',
    anim_clear: 'Clear All',
    anim_speed: 'Speed (FPS)',
    anim_preview: 'Add frames to preview',
    anim_add: 'Add Frames',
    dec_title: 'Base64 Decoder',
    dec_paste: 'Paste Base64 String',
    dec_preview: 'Preview',
    dec_invalid: 'Invalid Base64 string',
    dec_placeholder: 'Preview will appear here',
    set_title: 'Settings',
    set_theme: 'Theme',
    set_lang: 'Language',
    set_api: 'Google Gemini API Key',
    set_api_desc: 'Enter your own API key to use AI features without limits.',
    set_api_placeholder: 'Paste your API key here...',
    set_api_help: 'Get your API Key here',
    set_close: 'Close',
    set_color: 'Accent Color',
    set_save: 'Save Settings'
  },
  vi: {
    app_title: 'ImageLite',
    app_subtitle: 'Studio',
    client_secure: 'Xử lý bảo mật tại trình duyệt',
    docs: 'Tài liệu',
    tool_compress: 'Nén ảnh',
    tool_compress_desc: 'Giảm dung lượng',
    tool_convert: 'Chuyển WebP',
    tool_convert_desc: 'Tối ưu SEO',
    tool_avif: 'Chuyển AVIF',
    tool_avif_desc: 'Nén thế hệ mới',
    tool_base64: 'Base64',
    tool_base64_desc: 'Mã nhúng',
    tool_anim: 'Tạo GIF',
    tool_anim_desc: 'Ảnh động',
    tool_decode: 'Giải mã',
    tool_decode_desc: 'Base64 sang Ảnh',
    upload_title_drag: 'Thả ảnh vào đây',
    upload_title_click: 'Kéo thả hoặc chọn ảnh',
    upload_support: 'Hỗ trợ JPG, PNG, WebP, AVIF tối đa 50MB',
    processing: 'Đang xử lý ảnh...',
    results_empty_title: 'Kết quả sẽ hiện ở đây',
    results_empty_desc: 'Ảnh đã xử lý và file động sẽ xuất hiện tại đây.',
    did_you_know_title: 'Bạn có biết?',
    did_you_know_desc: 'AVIF có hiệu suất nén vượt trội hơn WebP và JPEG, giúp ảnh nhỏ gọn nhưng vẫn giữ chất lượng cao nhất.',
    res_visual: 'So sánh',
    res_embed: 'Mã nhúng',
    res_seo: 'Phân tích AI',
    res_before: 'Trước',
    res_after: 'Sau',
    res_download: 'Tải xuống',
    res_suggested_alt: 'Thẻ Alt gợi ý',
    res_caption: 'Mô tả / Caption',
    res_analyzing: 'Đang phân tích...',
    res_waiting: 'Đang chờ AI...',
    res_generated_by: 'Được tạo bởi Gemini 2.5 Flash',
    anim_title: 'Chế độ Hoạt hình',
    anim_desc: 'Ghép nhiều ảnh thành chuỗi động.',
    anim_clear: 'Xóa hết',
    anim_speed: 'Tốc độ (FPS)',
    anim_preview: 'Thêm ảnh để xem trước',
    anim_add: 'Thêm khung hình',
    dec_title: 'Giải mã Base64',
    dec_paste: 'Dán chuỗi Base64',
    dec_preview: 'Xem trước',
    dec_invalid: 'Chuỗi Base64 không hợp lệ',
    dec_placeholder: 'Ảnh xem trước sẽ hiện ở đây',
    set_title: 'Cài đặt',
    set_theme: 'Giao diện',
    set_lang: 'Ngôn ngữ',
    set_api: 'Google Gemini API Key',
    set_api_desc: 'Nhập API key của bạn để dùng tính năng AI không giới hạn.',
    set_api_placeholder: 'Dán API key vào đây...',
    set_api_help: 'Lấy API Key tại đây',
    set_close: 'Đóng',
    set_color: 'Màu chủ đạo',
    set_save: 'Lưu cài đặt'
  }
};

export const t = (lang: Language, key: TranslationKey): string => {
  return translations[lang][key] || translations['en'][key] || key;
};